# yamllint disable rule:line-length
name: Test for BuildEnv L1 container build

on:
  push:
    branches:
      - main
    paths:
      - 'build-container/**'

permissions:
  id-token: write
  attestations: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build docker container
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: "."
          file: "build-container/test-buildenv.dockerfile"
          tags: "test_l1:latest"

      - name: Generate SLSA Provenance
        id: slsa
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-name: "test_l1"
          subject-digest: ${{ steps.build.outputs.digest }}
